image: node:alpine
default: 
  tags: [worker01]


stages:
  - build
 # - deploy

cache:
  paths:
  -  node_modules/

build process:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

#deploy to surge:
#  stage: deploy
#  script:
#    - npx surge --project ./dist --domain xxx.surge.sh