image: node:latest
default: 
  tags: [worker2]

stages:
  - build


build_image:
  image: node:latest
  stage: build
  script:
    - npm link @angular/cli@14.1.0
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull