image: node:latest
default: 
  tags: [worker2]

stages:
  - build

build_image:
  stage: build
  script:
    - npm install
    - npm install -g @angular/cli
    - npm i @angular-devkit/build-angular --force
    - npm run build --source-map=false
    - npm run build --verbose --aot=false --optimization=true --sourceMap=false --buildOptimizer=false
    - ls

    # - npm install
    # - npm install -g @angular/cli
    # - npm i @angular-devkit/build-angular --force
    # - npm run build --verbose --aot=false --sourceMap=false --buildOptimizer=false
    # - ls
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  when: always



# image: node:alpine
# default: 
#   tags: [worker01]


# stages:
#   - build
# #  - test
#  # - deploy

# before_script:
#   - npm install

# build-min-code:
#   stage: build
#   script:
#     - npm install

#run-unit-test:
#  stage: test
#  script:
#    - npm run test#

#deploy-staging:
#  stage: deploy
#  script:
#    - npm run deploy-stage
#  only:
#    - develop#

#deploy-production:
#  stage: deploy
#  script:
#    - npm run deploy-prod
#  only:
#    - master
