image: alpine:latest
default: 
  tags: [worker01]

stages:
  - build
  - run_frontend_part

.install_prereq:
  before_script:
    - apk update
    - apk add ansible
    - apk add git
    - apk add python3
    - apk add tar


run_frontend_part:
  extends: .install_prereq
  stage: run_frontend_part
  script:
    - 'git clone https://oauth2:"$ANSIBLE_REPO_TOKEN"@mugiwara.gitlab.yandexcloud.net/mygroup/ansible.git'
    - cat $PRIVATE_KEY > /builds/mygroup/frontend/ansible/id_rsa
    - chmod 600 /builds/mygroup/frontend/ansible/id_rsa
    - cd /builds/mygroup/frontend && tar -czvf dist.tar.gz ./dist
    - cd /builds/mygroup/frontend/ansible && ansible-playbook frontend.yaml -e 'ansible_ssh_private_key_file=id_rsa' -e 'ansible_user=devuser' -e 'ansible_sudo_pass=$WORKER_PASS'
  when: always

# build_image:
#   stage: build
#   script:
#     - npm install
#     - npm install -g @angular/cli
#     - npm i @angular-devkit/build-angular --force
#     - npm run build --source-map=false
#     # - npm run build --verbose --aot=false --optimization=true --sourceMap=false --buildOptimizer=false
#     - ls -la

#     # - npm install
#     # - npm install -g @angular/cli
#     # - npm i @angular-devkit/build-angular --force
#     # - npm run build --verbose --aot=false --sourceMap=false --buildOptimizer=false
#     # - ls
#   artifacts:
#     paths:
#       - $CI_PROJECT_DIR/dist
#   when: always
